### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by mostafashraf18** [ehabAbdelMawla/Exhaust#15]
The done button make the app lags, the sign up page if you write the password short and rewrite it, it doesn't accept to sign it up for instead you've to go back to the log in page and click on the sign up button again

**Comment by ehabAbdelMawla** [comment]
Thanks for trying ,
But this is not the correct repo for your issue 
But i will solve this issue ASAP

**Comment by mostafashraf18** [comment]
Oh, I'm sorry
